spring:
  profiles:
    active: production

---
server:
  port: 9091
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://38.242.219.131:9011/.well-known/jwks.json
          issuer-uri: http://38.242.219.131:9011/
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://38.242.219.131:37821/ratiba_test
    username: keycloak
    password: keycloak
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: ee89e25c-6adf-45df-9abd-57bd5a8307af
      client-secret: xJGeaBz8N3TaoZadLTaLbGGaMKSkuk2X1os2Drewml0
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    enabled: true
#    path: /swagger-ui
oidc:
  issuer: ratiba.com
  auth_url: http://38.242.219.131:9011/oauth2/authorize
  token_url: http://38.242.219.131:9011/oauth2/token
---
server:
  port: 9090
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/kangethe.me/kangethe.me.keystore
    key-store-password: kangethe
    key-store-type: PKCS12
    key-alias: kangethe.me
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://38.242.219.131:9011/.well-known/jwks.json
          issuer-uri: http://38.242.219.131:9011/
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://38.242.219.131:37821/ratiba_test
    username: keycloak
    password: keycloak
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: ee89e25c-6adf-45df-9abd-57bd5a8307af
      client-secret: xJGeaBz8N3TaoZadLTaLbGGaMKSkuk2X1os2Drewml0
oidc:
  issuer: ratiba.com
  auth_url: http://38.242.219.131:9011/oauth2/authorize
  token_url: http://38.242.219.131:9011/oauth2/token

