name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ikangethe/ratiba:latest
  deploy_to_kangethe-server:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Kangethe Server
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop ratiba-container
            docker rm ratiba-container
            docker pull ikangethe/ratiba-container:latest
            docker run -d -p "9090:9090" --restart=unless-stopped --name=ratiba-container ikangethe/ratiba-container:latest
            docker ps -a